# Generated by Django 3.2 on 2021-04-20 21:41

from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('max_score', models.IntegerField(default=10)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=task.models.user_directory_path, validators=[task.models.validate_file_size])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('assessed', 'Assessed')], default='assigned', max_length=10)),
                ('comment', models.TextField(default='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
